name: Jira Ticket Enforcement

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches-ignore:
      - main
      - staging
      - develop

jobs:
  enforce-jira-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name for Jira Ticket
        if: github.event_name == 'push'
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          # Jira ticket pattern (modify to match your project keys)
          JIRA_PATTERN="[CYVD]+-[0-9]+"
          
          echo "Checking branch name: $BRANCH_NAME"
          
          if echo "$BRANCH_NAME" | grep -qE "$JIRA_PATTERN"; then
            echo "✅ Branch name contains Jira ticket reference"
          else
            echo "❌ Branch name must contain a Jira ticket reference (e.g., feature/CYVD-123-new-feature)"
            echo "Current branch: $BRANCH_NAME"
            echo "Expected format: feature/CYVD-123-description or bugfix/CYVD-456-fix-description"
            exit 1
          fi

      - name: Check PR Title and Description for Jira Ticket
        if: github.event_name == 'pull_request'
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          
          # Jira ticket pattern (modify to match your project keys)
          JIRA_PATTERN="[CYVD]+-[0-9]+"
          
          echo "Checking PR: $PR_TITLE"
          echo "Branch: $PR_BRANCH"
          
          # Check if PR title, body, or branch contains Jira ticket
          if echo "$PR_TITLE $PR_BODY $PR_BRANCH" | grep -qE "$JIRA_PATTERN"; then
            echo "✅ Jira ticket reference found in PR"
            
            # Extract ticket number for display
            TICKET=$(echo "$PR_TITLE $PR_BODY $PR_BRANCH" | grep -oE "$JIRA_PATTERN" | head -1)
            echo "Found ticket: $TICKET"
          else
            echo "❌ No Jira ticket reference found"
            echo "Please include a Jira ticket reference in:"
            echo "  - PR title (e.g., '[CYVD-123] Add new feature')"
            echo "  - PR description (e.g., 'Fixes CYVD-123')"
            echo "  - Branch name (e.g., 'feature/CYVD-123-new-feature')"
            exit 1
          fi

      - name: Validate Jira Ticket Format
        run: |
          echo "✅ Jira ticket format validation passed"
          echo "This check ensures all code changes are traceable to Jira tickets for SOC2 compliance"
